# Generated by Django 5.2.8 on 2025-11-29 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okere', '0002_newsimagestore_newsvideostore_servicestore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimagestore',
            name='show_in_recent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsvideostore',
            name='show_in_recent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SlideStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='SLIDE IMAGE')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_at'],
            },
        ),
    ]
