# Generated by Django 5.2.8 on 2025-12-02 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okere', '0003_newsimagestore_show_in_recent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_upload', models.FileField(upload_to='document/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_at'],
            },
        ),
        migrations.CreateModel(
            name='TouristImageStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_image', models.ImageField(upload_to='tourist/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_at'],
            },
        ),
        migrations.CreateModel(
            name='TouristVideoStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_video', models.ImageField(upload_to='tourist/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_at'],
            },
        ),
    ]
