# Generated by Django 5.2.8 on 2025-12-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okere', '0004_documentstore_touristimagestore_touristvideostore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristimagestore',
            name='tourist_image',
            field=models.ImageField(upload_to='TOURIST IMAGE/'),
        ),
        migrations.AlterField(
            model_name='touristvideostore',
            name='tourist_video',
            field=models.FileField(upload_to='TOURIST VIDEO/'),
        ),
    ]
